#!/bin/sh
ansi_red="\033[1;31m";
ansi_white="\033[1;37m";
ansi_green="\033[1;32m";
ansi_std="\033[m";
ENABLED=yes
PROCS=nginx
PREARGS=""
DESC=Nginx
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

case $1 in
	start)
		ARGS=""
		. /opt/etc/init.d/rc.func
		;;
	stop | kill)
		ARGS="-s quit"
		. /opt/etc/init.d/rc.func
		;;
	restart)
		ARGS="-s quit"
		. /opt/etc/init.d/rc.func stop
		ARGS=""
		. /opt/etc/init.d/rc.func start
		;;
	check)
		ARGS=""
		. /opt/etc/init.d/rc.func
		;;
	reload)
		echo -e -n "$ansi_white Reloading Nginx conf...       "
		nginx -s reload && echo -e "$ansi_green done." || echo -e "$ansi_red failed.$ansi_std"
		;;
		reopen)
		echo -e -n "$ansi_white Reopening Nginx log files...  "
		nginx -s reopen && echo -e "$ansi_green done." || echo -e "$ansi_red failed.$ansi_std"
		;;
	test)
		nginx -t
		;;
	*)
		echo -e "$ansi_white Usage: $0 (start|stop|restart|check|kill|reload|reopen|test)$ansi_std"
		;;
esac
